### ISSUE TITLE
[BUG] Failed to install the Microsoft.AzureMonitor.Containers.Metrics Arc extension on AKS EE

### ISSUE THREAD

**Issue by syedhassaanahmed** [Azure/AKS-Edge#138]
**Describe the bug**
Following [these docs](https://learn.microsoft.com/en-us/azure/azure-monitor/containers/prometheus-metrics-from-arc-enabled-cluster?tabs=cli#create-an-extension-instance) I'm trying to collect Prometheus metrics from an Arc-enabled AKS Edge Essentials Kubernetes cluster but have failed to install the `Microsoft.AzureMonitor.Containers.Metrics` Arc extension.

**To Reproduce**
1. Run command
```Powershell
az k8s-extension create --name azuremonitor-metrics --cluster-name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --cluster-type connectedClusters --extension-type Microsoft.AzureMonitor.Containers.Metrics
```
2. See error
```
(ExtensionOperationFailed) The extension operation failed with the following error:  
Error: [ InnerError: [Helm installation failed : 
Timed out waiting for the resource to come to a ready/completed stateDeployment is not ready: 
kube-system/ama-metrics. 0 out of 1 expected pods are ready : 
Recommendation Please contact Microsoft support for further inquiries : 
InnerError [release azuremonitor-metrics failed, and has been uninstalled due to atomic being set: 
timed out waiting for the condition]]] occurred while doing the operation : 
[Create] on the config.
```
From kubectl logs the `prometheus-collector` container is stuck at `ContainerCreating` and the following can be seen from the events
```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    3m47s                default-scheduler  Successfully assigned kube-system/ama-metrics-794786cdfb-cfsln to <windows-device-name>
  Warning  FailedMount  3m46s                kubelet            MountVolume.SetUp failed for volume "ama-metrics-proxy-cert" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  104s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[anchors-ubuntu], unattached volumes=[settings-vol-config prometheus-config-vol host-log-containers host-log-pods anchors-mariner anchors-ubuntu ama-metrics-proxy-cert kube-api-access-866x4]: timed out waiting for the condition
  Warning  FailedMount  99s (x9 over 3m47s)  kubelet            MountVolume.SetUp failed for volume "anchors-ubuntu" : mkdir /usr/local/share/ca-certificates/: read-only file system
```

**Expected behavior**
The `Microsoft.AzureMonitor.Containers.Metrics` Arc extension is successfully installed.

**Environment (please complete the following information):**
 - AKS Edge Essentials Version v1.2.414.0
 - Kubernetes version v1.25.4
 - Windows Host OS: 11 Enterprise 22H2
    - Version: 10.0.22621 Build 22621
    - Virtual Machine: None

**Additional context**
```json
"LinuxNode": {
        "CpuCount": 4,
        "MemoryInMB": 8192,
        "DataSizeInGB": 30
}
```

**Comment by fcabrera23** [comment]
Hi @syedhassaanahmed,

Thanks for reaching out. We are aware of this issue and are currently working with the Azure Monitor team (@gracewehner) to fix this in our upcoming versions. 

Thanks,
Francisco

**Comment by gracewehner** [comment]
Hi @syedhassaanahmed, this should be working now with the latest extension version for Microsoft.AzureMonitor.Containers.Metrics

**Comment by syedhassaanahmed** [comment]
@fcabrera23 @gracewehner In which version of AKS EE and the extension version should it be working? I was still able to reproduce the issue with the latest.
AKS EE: `1.3.186.0`
Microsoft.AzureMonitor.Containers.Metrics: `6.7.4-main-08-11-2023-6de2ec55`

**Comment by fcabrera23** [comment]
Hi,

I'm reopening this issue as users are still seeing the issue.  We will continue investigating and provide an update as soon as possible.

Thanks,
Francisco

**Comment by JMayrbaeurl** [comment]
I've checked the KubeEvents logs for my AKS EE and it looks like the root cause is the following:

Reason: `FailedMount`
Message: `MountVolume.SetUp failed for volume "anchors-ubuntu" : mkdir /usr/local/share/ca-certificates/: read-only file system`

This is followed by `Unable to attach or mount volumes: unmounted volumes=[anchors-ubuntu], unattached volumes=[anchors-ubuntu ama-metrics-proxy-cert kube-api-access-nxm7l settings-vol-config prometheus-config-vol host-log-containers host-log-pods anchors-mariner]: timed out waiting for the condition`

**Comment by fcabrera23** [comment]
Hi @JMayrbaeurl,

Thanks for the information. We are aware of the mounting issue, and we have already added a fix, but for unknown reasons the fix is not working with some clusters.

1. Are you connecting your cluster to Arc K8s with the azcli?
2. If so, could you please try connecting using the AKS-EE `Connect-AksEdgeArc` cmdlet instead?

Thanks,
Francisco

**Comment by JMayrbaeurl** [comment]
Hi @fcabrera23 ,

I think I've used azcli to connect my cluster to Arc according to the Quickstart guidance of Alice Springs. And since we are currently doing Alice Springs testing I'm not able to disconnect/reconnect my current installation. Otherwise I would like to use the Observability features. Any idea to fix it w/o the need of reconnecting?

**Comment by fcabrera23** [comment]
Hi @JMayrbaeurl,

Thanks for the confirmation. The best option is to reconnect to Arc using the `Connect-AksEdgeArc` PS cmdlet. We are working on a fix for the azcli option but could take some days.

Thanks,
Francisco

**Comment by syedhassaanahmed** [comment]
@fcabrera23 Thanks for the update. I was able to make the Metrics extension work on AKS EE by connecting to Arc using `Connect-AksEdgeArc`
For AKS EE clusters provisioned using [Arc Jumpstart](https://github.com/microsoft/azure_arc/blob/b4444b491e72dbfd1923eb01dbfb439df274a035/azure_arc_k8s_jumpstart/aks_hybrid/aks_edge_essentials_single/arm_template/artifacts/LogonScript.ps1#L238-L242) it currently won't be possible to install the Metrics extension by default until it is manually disconnected/reconnected to Arc.

**Comment by JMayrbaeurl** [comment]
Disconnecting and reconnecting seems to be no option for me, because I assume that I'll loose my complete k8s Alice Springs setup, that's primarily working with Kubernetes extensions. Right?

**Comment by fcabrera23** [comment]
Hi @JMayrbaeurl,

Sorry for the inconvenience.  Given that Alice Springs requires a connected cluster, you will need to reconnect and then redeploy Alice Springs.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @JMayrbaeurl,

Sorry for the inconvenience.  Given that Alice Springs requires a connected cluster, you will need to reconnect and then redeploy Alice Springs.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi,

This issue was fixed with the latest `az cli connectk8s` extension. Please ensure to use the version v1.5.3 or greater.

Thanks,
Francisco
